from pathlib import Path
import re
import xml.etree.ElementTree as ET
ROOT=Path('android-nadaye');APP=ROOT/'app';JAVA=APP/'src/main/java/com/nadaye/beheshti'
ANDROID_NS='http://schemas.android.com/apk/res/android';A='{%s}'%ANDROID_NS;ET.register_namespace('android',ANDROID_NS)

gradle=APP/'build.gradle';s=gradle.read_text(encoding='utf-8');s=re.sub(r'versionCode\s+\d+','versionCode 7',s);s=re.sub(r"versionName\s+['\"][^'\"]+['\"]","versionName '4.2.0'",s);gradle.write_text(s,encoding='utf-8')
manifest=APP/'src/main/AndroidManifest.xml';tree=ET.parse(manifest);root=tree.getroot();perms={x.get(A+'name') for x in root.findall('uses-permission')}
for p in ['android.permission.WAKE_LOCK','android.permission.ACCESS_NETWORK_STATE']:
    if p not in perms: el=ET.Element('uses-permission');el.set(A+'name',p);root.insert(0,el)
application=root.find('application');application.set(A+'allowBackup','false');application.set(A+'fullBackupContent','false');application.set(A+'icon','@mipmap/ic_launcher');application.set(A+'roundIcon','@mipmap/ic_launcher_round')
boot=None
for r in application.findall('receiver'):
    if r.get(A+'name') in ('.BootReceiver','com.nadaye.beheshti.BootReceiver'):boot=r;break
if boot is None:boot=ET.SubElement(application,'receiver');boot.set(A+'name','.BootReceiver');boot.set(A+'exported','true')
intent=boot.find('intent-filter')
if intent is None:intent=ET.SubElement(boot,'intent-filter')
actions={x.get(A+'name') for x in intent.findall('action')}
for action in ['android.intent.action.BOOT_COMPLETED','android.intent.action.TIME_SET','android.intent.action.TIMEZONE_CHANGED','android.intent.action.DATE_CHANGED','android.intent.action.MY_PACKAGE_REPLACED']:
    if action not in actions:x=ET.SubElement(intent,'action');x.set(A+'name',action)
manifest.write_text(ET.tostring(root,encoding='unicode'),encoding='utf-8')

(JAVA/'PrayerTimes.java').write_text(r'''package com.nadaye.beheshti;
import java.text.SimpleDateFormat;import java.util.*;
public final class PrayerTimes{
 private PrayerTimes(){} public static final class Result{public final LinkedHashMap<String,Long> millis=new LinkedHashMap<>();public String get(String k){Long v=millis.get(k);return v==null?"--:--":fmt(v);}}
 public static Result calculate(long dayMillis,double latitude,double longitude){Calendar c=Calendar.getInstance();c.setTimeInMillis(dayMillis);c.set(Calendar.HOUR_OF_DAY,12);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);int n=c.get(Calendar.DAY_OF_YEAR);double g=2*Math.PI/365.0*(n-1);double eq=229.18*(0.000075+0.001868*Math.cos(g)-0.032077*Math.sin(g)-0.014615*Math.cos(2*g)-0.040849*Math.sin(2*g));double dec=0.006918-0.399912*Math.cos(g)+0.070257*Math.sin(g)-0.006758*Math.cos(2*g)+0.000907*Math.sin(2*g)-0.002697*Math.cos(3*g)+0.00148*Math.sin(3*g);double tz=TimeZone.getDefault().getOffset(c.getTimeInMillis())/3600000.0;double noon=720-4*longitude-eq+tz*60;double rise=noon-angleMinutes(latitude,dec,-0.833),set=noon+angleMinutes(latitude,dec,-0.833),fr=noon-angleMinutes(latitude,dec,-16),mr=noon+angleMinutes(latitude,dec,-4),ir=noon+angleMinutes(latitude,dec,-14);double night=(1440-set)+rise;if(!Double.isFinite(rise)||!Double.isFinite(set)||night<1){rise=noon-360;set=noon+360;night=720;}double fajr=before(rise,fr,night,16),maghrib=after(set,mr,night,4),isha=after(set,ir,night,14);Result r=new Result();r.millis.put("فجر",toMs(c,fajr));r.millis.put("طلوع",toMs(c,rise));r.millis.put("ظهر",toMs(c,noon));r.millis.put("مغرب",toMs(c,maghrib));r.millis.put("عشاء",toMs(c,isha));return r;}
 private static double before(double ref,double raw,double night,double a){double lim=night*a/60.0;return !Double.isFinite(raw)||ref-raw>lim?ref-lim:raw;} private static double after(double ref,double raw,double night,double a){double lim=night*a/60.0;return !Double.isFinite(raw)||raw-ref>lim?ref+lim:raw;}
 private static double angleMinutes(double latDeg,double dec,double altDeg){double lat=Math.toRadians(Math.max(-89.8,Math.min(89.8,latDeg))),alt=Math.toRadians(altDeg),den=Math.cos(lat)*Math.cos(dec);if(Math.abs(den)<1e-12)return Double.NaN;double ch=(Math.sin(alt)-Math.sin(lat)*Math.sin(dec))/den;if(ch < -1 || ch > 1)return Double.NaN;return Math.toDegrees(Math.acos(ch))*4;}
 private static long toMs(Calendar b,double min){Calendar d=(Calendar)b.clone();d.set(Calendar.HOUR_OF_DAY,0);d.set(Calendar.MINUTE,0);d.set(Calendar.SECOND,0);d.set(Calendar.MILLISECOND,0);return d.getTimeInMillis()+Math.round(min*60000);}
 public static String fmt(long ms){return new SimpleDateFormat("HH:mm",new Locale("fa")).format(new Date(ms));} public static String nextPrayer(Result r,long now){for(Map.Entry<String,Long> e:r.millis.entrySet()){if("طلوع".equals(e.getKey()))continue;if(e.getValue()>now)return e.getKey()+"  "+fmt(e.getValue());}return "فجر فردا";}
}''',encoding='utf-8')

(JAVA/'AlarmReceiver.java').write_text(r'''package com.nadaye.beheshti;import android.app.*;import android.content.*;import android.os.Build;import java.util.*;
public class AlarmReceiver extends BroadcastReceiver{static final String[] LABELS={"فجر","ظهر","مغرب","عشاء"};@Override public void onReceive(Context c,Intent i){if(!c.getSharedPreferences("nadaye",0).getBoolean("notifications",true))return;String l=i==null?null:i.getStringExtra("label");AdhanService.start(c,l==null?"وقت نماز":l);scheduleToday(c);}public static void scheduleToday(Context c){if(!c.getSharedPreferences("nadaye",0).getBoolean("notifications",true))return;double lat=Double.longBitsToDouble(c.getSharedPreferences("nadaye",0).getLong("lat",Double.doubleToLongBits(34.5553))),lon=Double.longBitsToDouble(c.getSharedPreferences("nadaye",0).getLong("lon",Double.doubleToLongBits(69.2075)));long now=System.currentTimeMillis();Calendar day=Calendar.getInstance();for(int d=0;d<2;d++){Calendar x=(Calendar)day.clone();x.add(Calendar.DAY_OF_YEAR,d);PrayerTimes.Result r=PrayerTimes.calculate(x.getTimeInMillis(),lat,lon);for(int n=0;n<LABELS.length;n++){Long w=r.millis.get(LABELS[n]);if(w!=null&&w>now)schedule(c,LABELS[n],w,code(x,n));}}}static int code(Calendar x,int n){return Math.abs((x.get(Calendar.YEAR)%100)*10000+x.get(Calendar.DAY_OF_YEAR)*10+n);}static void schedule(Context c,String l,long w,int id){AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(am==null)return;PendingIntent pi=PendingIntent.getBroadcast(c,id,new Intent(c,AlarmReceiver.class).putExtra("label",l),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);try{if(Build.VERSION.SDK_INT>=31&&!am.canScheduleExactAlarms())am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,w,pi);else if(Build.VERSION.SDK_INT>=23)am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,w,pi);else am.setExact(AlarmManager.RTC_WAKEUP,w,pi);}catch(Exception e){try{if(Build.VERSION.SDK_INT>=23)am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,w,pi);else am.set(AlarmManager.RTC_WAKEUP,w,pi);}catch(Exception ignored){}}}public static void cancelAll(Context c){AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(am==null)return;Calendar day=Calendar.getInstance();for(int d=-1;d<=2;d++){Calendar x=(Calendar)day.clone();x.add(Calendar.DAY_OF_YEAR,d);for(int n=0;n<LABELS.length;n++){PendingIntent pi=PendingIntent.getBroadcast(c,code(x,n),new Intent(c,AlarmReceiver.class),PendingIntent.FLAG_NO_CREATE|PendingIntent.FLAG_IMMUTABLE);if(pi!=null)am.cancel(pi);}}}}
''',encoding='utf-8')
(JAVA/'BootReceiver.java').write_text('package com.nadaye.beheshti;import android.content.*;public class BootReceiver extends BroadcastReceiver{@Override public void onReceive(Context c,Intent i){AlarmReceiver.scheduleToday(c);}}',encoding='utf-8')
(JAVA/'AdhanService.java').write_text(r'''package com.nadaye.beheshti;import android.app.*;import android.content.*;import android.media.*;import android.net.Uri;import android.os.*;
public class AdhanService extends Service{static final String CHANNEL="nadaye_adhan",STOP="com.nadaye.beheshti.STOP_ADHAN";MediaPlayer player;public static void start(Context c,String label){Intent i=new Intent(c,AdhanService.class).putExtra("label",label);if(Build.VERSION.SDK_INT>=26)c.startForegroundService(i);else c.startService(i);}@Override public void onCreate(){super.onCreate();if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(CHANNEL,"اذان ندای بهشتی",NotificationManager.IMPORTANCE_HIGH);ch.enableVibration(true);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(ch);}}@Override public int onStartCommand(Intent i,int f,int id){if(i!=null&&STOP.equals(i.getAction())){stopNow();return START_NOT_STICKY;}String l=i==null?"وقت نماز":i.getStringExtra("label");Intent si=new Intent(this,AdhanService.class).setAction(STOP);PendingIntent stop=PendingIntent.getService(this,991,si,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,CHANNEL):new Notification.Builder(this);b.setSmallIcon(R.drawable.ic_launcher).setContentTitle("ندای بهشتی — "+(l==null?"وقت نماز":l)).setContentText("وقت نماز فرا رسیده است").setOngoing(true).addAction(android.R.drawable.ic_media_pause,"توقف",stop);startForeground(2001,b.build());play();new Handler(Looper.getMainLooper()).postDelayed(this::stopNow,6*60*1000L);return START_NOT_STICKY;}void play(){try{String s=getSharedPreferences("nadaye",0).getString("adhan_uri","");Uri u=s==null||s.trim().isEmpty()?Uri.parse("android.resource://"+getPackageName()+"/"+R.raw.default_adhan):Uri.parse(s);player=new MediaPlayer();player.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build());player.setDataSource(this,u);player.setOnPreparedListener(MediaPlayer::start);player.setOnCompletionListener(x->stopNow());player.setOnErrorListener((x,w,e)->{fallback();return true;});player.prepareAsync();}catch(Exception e){fallback();}}void fallback(){try{if(player!=null){player.release();player=null;}player=MediaPlayer.create(this,R.raw.default_adhan);if(player!=null){player.setOnCompletionListener(x->stopNow());player.start();}else stopNow();}catch(Exception e){stopNow();}}void stopNow(){try{if(player!=null){if(player.isPlaying())player.stop();player.release();player=null;}}catch(Exception ignored){}stopForeground(true);stopSelf();}@Override public void onDestroy(){try{if(player!=null)player.release();}catch(Exception ignored){}super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}}
''',encoding='utf-8')

main=JAVA/'MainActivity.java';m=main.read_text(encoding='utf-8')
if 'void ensureExactAlarmAccess()' not in m:
    h='\n    void ensureExactAlarmAccess(){if(Build.VERSION.SDK_INT<31)return;try{AlarmManager am=(AlarmManager)getSystemService(ALARM_SERVICE);if(am!=null&&!am.canScheduleExactAlarms())startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM,Uri.parse("package:"+getPackageName())));}catch(Exception ignored){}}\n\n'
    marker='    void immersive(boolean yes)';m=m.replace(marker,h+marker,1) if marker in m else m
if 'ensureExactAlarmAccess();' not in m.split('void ensureExactAlarmAccess()',1)[0]:
    m,n=re.subn(r'(super\.onCreate\s*\([^;]+;)',r'\1\n        ensureExactAlarmAccess();\n        try { AlarmReceiver.scheduleToday(this); } catch (Exception ignored) { }\n        refreshLocationFresh(false);',m,count=1)
    if n==0:raise SystemExit('super.onCreate not found')
if 'void refreshLocationFresh(boolean toast)' not in m:
    helper=r'''
    void refreshLocationFresh(boolean toast){
        if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;
        try{final LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);LocationListener once=new LocationListener(){@Override public void onLocationChanged(Location l){if(l!=null){prefs.edit().putLong("lat",Double.doubleToLongBits(l.getLatitude())).putLong("lon",Double.doubleToLongBits(l.getLongitude())).apply();AlarmReceiver.cancelAll(MainActivity.this);AlarmReceiver.scheduleToday(MainActivity.this);if(toast)toast("موقعیت تازه شد");try{lm.removeUpdates(this);}catch(Exception ignored){}}}@Override public void onProviderEnabled(String p){}@Override public void onProviderDisabled(String p){}@Override public void onStatusChanged(String p,int s,Bundle e){}};String provider=lm.isProviderEnabled(LocationManager.GPS_PROVIDER)?LocationManager.GPS_PROVIDER:LocationManager.NETWORK_PROVIDER;lm.requestSingleUpdate(provider,once,Looper.getMainLooper());Location best=null;for(String p:lm.getProviders(true)){Location l=lm.getLastKnownLocation(p);if(l!=null&&(best==null||l.getTime()>best.getTime()))best=l;}if(best!=null&&System.currentTimeMillis()-best.getTime()<21600000L){prefs.edit().putLong("lat",Double.doubleToLongBits(best.getLatitude())).putLong("lon",Double.doubleToLongBits(best.getLongitude())).apply();}else if(toast)toast("در حال دریافت موقعیت تازه…");}catch(Exception e){if(toast)toast("دسترسی موقعیت ممکن نشد");}
    }
'''
    marker='    void immersive(boolean yes)';m=m.replace(marker,helper+marker,1) if marker in m else m
m=m.replace('refreshLocation(false);','refreshLocation(false); refreshLocationFresh(false);').replace('نسخه ۴٫۱','نسخه ۴٫۲').replace('نسخه ۴.۱','نسخه ۴.۲').replace('نسخه ۴ •','نسخه ۴.۲ •');main.write_text(m,encoding='utf-8')

values=APP/'src/main/res/values';values.mkdir(parents=True,exist_ok=True);(values/'launcher_colors.xml').write_text('<?xml version="1.0" encoding="utf-8"?>\n<resources><color name="launcher_bg">#FAF6EE</color></resources>\n',encoding='utf-8')
legacy=APP/'src/main/res/mipmap-anydpi';legacy.mkdir(parents=True,exist_ok=True);modern=APP/'src/main/res/mipmap-anydpi-v26';modern.mkdir(parents=True,exist_ok=True)
for name in ['ic_launcher','ic_launcher_round']:
    (legacy/f'{name}.xml').write_text('<?xml version="1.0" encoding="utf-8"?>\n<selector xmlns:android="http://schemas.android.com/apk/res/android"><item android:drawable="@drawable/ic_launcher"/></selector>\n',encoding='utf-8');(modern/f'{name}.xml').write_text('<?xml version="1.0" encoding="utf-8"?>\n<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android"><background android:drawable="@color/launcher_bg"/><foreground android:drawable="@drawable/ic_launcher"/></adaptive-icon>\n',encoding='utf-8')
assert 'versionCode 7' in gradle.read_text(encoding='utf-8');assert "versionName '4.2.0'" in gradle.read_text(encoding='utf-8');assert 'refreshLocationFresh' in main.read_text(encoding='utf-8');assert 'R.raw.default_adhan' in (JAVA/'AdhanService.java').read_text(encoding='utf-8');assert 'allowBackup="false"' in manifest.read_text(encoding='utf-8');print('Nadaye Beheshti 4.2 final hardening applied')