from pathlib import Path
p=Path('android-nadaye/app/src/main/java/com/nadaye/beheshti/MainActivity.java')
s=p.read_text(encoding='utf-8')

s=s.replace('static final String PREF="nadaye";','static final String PREF="nadaye";\n    static final String CENTRAL_BASE="https://nadaye-beheshti-central-ziua8x.v2.appdeploy.ai";',1)

s=s.replace('        showHome();\n    }','        showHome();\n        centralSyncAsync(false);\n    }',1)

old='String[] names={"رنگ‌ها و استایل","فونت و اندازه‌ها","تصاویر و قاب همراه معنوی","مدیریت تمام آیکن‌ها","زندگی‌نامه و اندیشه‌های آیت‌الله بهشتی","مدیریت صوت گنج معنوی","متن‌ها و عنوان‌ها","ابعاد و چیدمان دقیق صفحه اصلی","مدیریت موذن‌ها","ویرایش پیشرفته JSON","تغییر رمز پنل","بازنشانی فقط ظاهر"};\n        View.OnClickListener[] acts={v->showColorEditor(),v->showFontEditor(),v->showImageEditor(),v->showIconEditor(),v->showBeheshtiEditor(),v->showSpiritualAudioEditor(),v->showLabelEditor(),v->showLayoutEditor(),v->showMuezzinManager(),v->showJsonEditor(),v->changeAdminPin(),v->resetTheme()};'
new='String[] names={"انتشار طراحی فعلی برای همه","رنگ‌ها و استایل","فونت و اندازه‌ها","تصاویر و قاب همراه معنوی","مدیریت تمام آیکن‌ها","زندگی‌نامه و اندیشه‌های آیت‌الله بهشتی","مدیریت صوت گنج معنوی","متن‌ها و عنوان‌ها","ابعاد و چیدمان دقیق صفحه اصلی","مدیریت موذن‌ها","ویرایش پیشرفته JSON","تغییر رمز پنل","بازنشانی فقط ظاهر"};\n        View.OnClickListener[] acts={v->showCentralPublisher(),v->showColorEditor(),v->showFontEditor(),v->showImageEditor(),v->showIconEditor(),v->showBeheshtiEditor(),v->showSpiritualAudioEditor(),v->showLabelEditor(),v->showLayoutEditor(),v->showMuezzinManager(),v->showJsonEditor(),v->changeAdminPin(),v->resetTheme()};'
assert old in s
s=s.replace(old,new,1)

anchor='    // ---------- Hidden owner studio ----------\n'
assert anchor in s
methods=r'''    // ---------- Central owner publishing ----------
    boolean centralPrefKey(String k){return k.startsWith("theme.")||k.startsWith("home.")||k.startsWith("label.")||k.startsWith("icon.")||k.startsWith("spiritual.audio.")||k.startsWith("adhan.slot.");}
    JSONObject centralTyped(Object v)throws Exception{JSONObject o=new JSONObject();if(v instanceof Integer){o.put("t","i");o.put("v",v);}else if(v instanceof Long){o.put("t","l");o.put("v",v);}else if(v instanceof Float||v instanceof Double){o.put("t","f");o.put("v",((Number)v).doubleValue());}else if(v instanceof Boolean){o.put("t","b");o.put("v",v);}else{o.put("t","s");o.put("v",String.valueOf(v));}return o;}
    InputStream centralOpenLocal(String value)throws Exception{if(value==null||value.isEmpty())return null;if(value.startsWith("content://"))return getContentResolver().openInputStream(Uri.parse(value));if(value.startsWith("file://")){File f=new File(Uri.parse(value).getPath());return f.exists()?new FileInputStream(f):null;}File f=new File(value);return f.exists()?new FileInputStream(f):null;}
    String centralMime(String value){try{if(value!=null&&value.startsWith("content://")){String t=getContentResolver().getType(Uri.parse(value));if(t!=null)return t;}}catch(Exception ignored){}String x=value==null?"":value.toLowerCase(Locale.US);if(x.endsWith(".png"))return "image/png";if(x.endsWith(".webp"))return "image/webp";if(x.endsWith(".jpg")||x.endsWith(".jpeg"))return "image/jpeg";if(x.endsWith(".ttf"))return "font/ttf";if(x.endsWith(".otf"))return "font/otf";if(x.endsWith(".mp3"))return "audio/mpeg";if(x.endsWith(".ogg"))return "audio/ogg";return "application/octet-stream";}
    byte[] centralReadBytes(InputStream in)throws Exception{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[16384];int n,total=0;while((n=in.read(b))>0){total+=n;if(total>20*1024*1024)throw new IOException("asset_too_large");out.write(b,0,n);}in.close();return out.toByteArray();}
    String centralReadText(InputStream in)throws Exception{return new String(centralReadBytes(in),"UTF-8");}
    JSONObject centralHttp(String method,String path,JSONObject body)throws Exception{URL u=new URL(CENTRAL_BASE+path);HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(12000);c.setReadTimeout(30000);c.setRequestMethod(method);c.setRequestProperty("Accept","application/json");if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");byte[] d=body.toString().getBytes("UTF-8");OutputStream o=c.getOutputStream();o.write(d);o.close();}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();String txt=in==null?"{}":centralReadText(in);c.disconnect();if(code<200||code>=300)throw new IOException("HTTP "+code+" "+txt);return new JSONObject(txt);}
    String centralOwnerToken(){String t=prefs.getString("central.ownerToken","");if(t.length()>=32)return t;t=UUID.randomUUID().toString()+UUID.randomUUID().toString();prefs.edit().putString("central.ownerToken",t).apply();return t;}
    String centralUploadAsset(String token,String key,String value)throws Exception{InputStream in=centralOpenLocal(value);if(in==null)return null;byte[] data=centralReadBytes(in);String mime=centralMime(value);String ext=mime.contains("png")?".png":mime.contains("webp")?".webp":mime.contains("jpeg")?".jpg":mime.contains("ttf")?".ttf":mime.contains("otf")?".otf":mime.contains("mpeg")?".mp3":mime.contains("ogg")?".ogg":".bin";JSONObject q=new JSONObject();q.put("token",token);q.put("name","asset_"+Math.abs(key.hashCode())+ext);q.put("contentType",mime);q.put("content",android.util.Base64.encodeToString(data,android.util.Base64.NO_WRAP));return centralHttp("POST","/api/asset",q).optString("path","");}
    JSONObject buildCentralPayload(String token)throws Exception{JSONObject payload=new JSONObject(),vals=new JSONObject(),assets=new JSONObject();for(Map.Entry<String,?>e:prefs.getAll().entrySet()){String k=e.getKey();if(!centralPrefKey(k))continue;Object v=e.getValue();if(v instanceof String){String sv=(String)v;InputStream test=null;try{test=centralOpenLocal(sv);}catch(Exception ignored){}if(test!=null){try{test.close();}catch(Exception ignored){}String path=centralUploadAsset(token,k,sv);if(path!=null&&!path.isEmpty()){assets.put(k,path);continue;}}}vals.put(k,centralTyped(v));}payload.put("prefs",vals);payload.put("assets",assets);payload.put("beheshti",beheshtiEntries());payload.put("schema",1);return payload;}
    void showCentralPublisher(){ScrollView sc=scrollPage("انتشار مرکزی");LinearLayout b=body(sc);addCard(b,text("همین طراحی و محتوایی که خودتان در پنل مخفی تنظیم کرده‌اید، منبع اصلی همه نسخه‌ها می‌شود. ظاهر فعلی اپ تغییر نمی‌کند و تنظیمات شخصی کاربران مثل موقعیت، اعلان و ذکرشمار دست‌نخورده می‌ماند.",15,textColor(),true));addCard(b,text("نسخه مرکزی دریافت‌شده: "+prefs.getInt("central.version",0),13,textColor(),false));Button pub=button("انتشار همین تغییرات برای همه");pub.setOnClickListener(v->centralPublishAsync());b.addView(pub,new LinearLayout.LayoutParams(-1,dp(58)));Button sync=smallButton("دریافت دوباره نسخه مرکزی");sync.setOnClickListener(v->centralSyncAsync(true));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(52));lp.setMargins(0,dp(8),0,0);b.addView(sync,lp);}
    void centralPublishAsync(){toast("در حال انتشار...");new Thread(()->{try{String token=centralOwnerToken();JSONObject st=centralHttp("GET","/api/config",null);if(!st.optBoolean("published",false)){JSONObject claim=new JSONObject();claim.put("token",token);claim.put("payload",new JSONObject());centralHttp("POST","/api/claim",claim);}JSONObject payload=buildCentralPayload(token);JSONObject req=new JSONObject();req.put("token",token);req.put("payload",payload);JSONObject r=centralHttp("POST","/api/publish",req);int ver=r.optInt("version",prefs.getInt("central.version",0)+1);prefs.edit().putInt("central.version",ver).apply();runOnUiThread(()->{toast("برای همه منتشر شد — نسخه "+ver);showCentralPublisher();});}catch(Exception e){runOnUiThread(()->toast("انتشار مرکزی انجام نشد"));}}).start();}
    File centralDownloadAsset(String prefKey,String storagePath)throws Exception{String qp=java.net.URLEncoder.encode(storagePath,"UTF-8");JSONObject r=centralHttp("GET","/api/asset-url?path="+qp,null);String url=r.optString("url","");if(url.isEmpty())throw new IOException("no_asset_url");HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(30000);InputStream in=c.getInputStream();byte[] data=centralReadBytes(in);c.disconnect();String low=storagePath.toLowerCase(Locale.US),ext=low.endsWith(".png")?".png":low.endsWith(".webp")?".webp":low.endsWith(".jpg")||low.endsWith(".jpeg")?".jpg":low.endsWith(".ttf")?".ttf":low.endsWith(".otf")?".otf":low.endsWith(".mp3")?".mp3":low.endsWith(".ogg")?".ogg":".bin";File f=new File(getFilesDir(),"central_"+Math.abs(prefKey.hashCode())+ext);FileOutputStream o=new FileOutputStream(f);o.write(data);o.close();return f;}
    void applyCentralTyped(SharedPreferences.Editor ed,String key,JSONObject o){String t=o.optString("t","s");if("i".equals(t))ed.putInt(key,o.optInt("v"));else if("l".equals(t))ed.putLong(key,o.optLong("v"));else if("f".equals(t))ed.putFloat(key,(float)o.optDouble("v"));else if("b".equals(t))ed.putBoolean(key,o.optBoolean("v"));else ed.putString(key,o.optString("v",""));}
    void centralSyncAsync(boolean force){new Thread(()->{try{JSONObject cfg=centralHttp("GET","/api/config",null);if(!cfg.optBoolean("published",false))return;int remote=cfg.optInt("version",0),local=prefs.getInt("central.version",0);boolean owner=prefs.getString("central.ownerToken","").length()>=32;if(!force&&owner&&remote<=local)return;JSONObject payload=cfg.optJSONObject("payload");if(payload==null)return;JSONObject vals=payload.optJSONObject("prefs");SharedPreferences.Editor ed=prefs.edit();if(vals!=null){Iterator<String>it=vals.keys();while(it.hasNext()){String k=it.next();JSONObject tv=vals.optJSONObject(k);if(tv!=null)applyCentralTyped(ed,k,tv);}}ed.apply();JSONObject assets=payload.optJSONObject("assets");if(assets!=null){Iterator<String>it=assets.keys();while(it.hasNext()){String k=it.next(),sp=assets.optString(k,"");if(sp.isEmpty())continue;try{File f=centralDownloadAsset(k,sp);String v=(k.startsWith("spiritual.audio.")||k.startsWith("adhan.slot."))?Uri.fromFile(f).toString():f.getAbsolutePath();prefs.edit().putString(k,v).apply();}catch(Exception ignored){}}}JSONArray bh=payload.optJSONArray("beheshti");if(bh!=null)saveBeheshtiEntries(bh);prefs.edit().putInt("central.version",remote).apply();runOnUiThread(()->{if(atHome)showHome();if(force)toast("نسخه مرکزی دریافت شد");});}catch(Exception ignored){}}).start();}

'''
s=s.replace(anchor,methods+anchor,1)
p.write_text(s,encoding='utf-8')
print('Central publishing and sync added without changing existing UI design')
